# Generated by Django 2.1.2 on 2019-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='日時'),
        ),
    ]
