# Generated by Django 2.1.2 on 2019-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タグorライブラリ'),
        ),
    ]
