# Generated by Django 2.1.2 on 2019-08-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_solve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='solve',
            field=models.IntegerField(blank=True, choices=[('解決', '解決'), ('非解決', '非解決')], null=True, verbose_name='選択肢'),
        ),
    ]
