# Generated by Django 2.1.2 on 2019-08-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190813_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='solve',
            field=models.CharField(blank=True, choices=[('解決', '解決'), ('非解決', '非解決')], max_length=5, null=True, verbose_name='選択肢'),
        ),
    ]
