# Generated by Django 2.1.2 on 2019-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190813_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_contents',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
